name: "Build"

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: nix build -L --show-trace .#windows.installer
      - run: find . -type f -name "*.msi"
